import QtQuick
import QtCore
import org.kde.plasma.plasmoid
import org.kde.plasma.plasma5support as Plasma5Support
import org.kde.plasma.core as PlasmaCore
import "../js/HistoryManager.js" as HistoryManager
import "../js/PinnedManager.js" as PinnedManager
import "../js/CategoryManager.js" as CategoryManager
import "../js/TelemetryManager.js" as TelemetryManager
import "../js/ConfigManager.js" as ConfigManager
import "../js/utils.js" as Utils
import "../js/RSSManager.js" as RSSManager

Item {
    id: logicRoot
    
    // Required dependencies
    required property var plasmoidConfig
    // trFunc property removed
    
    // Signals
    // Signals
    signal historyForceUpdate()
    onHistoryForceUpdate: historyVersion++ // Increment version to trigger bindings
    
    // Reactive version counter for deep updates
    property int historyVersion: 0
    
    // pinnedItemsChanged is automatically generated by property definition

    
    // ===== CONFIGURATION MANAGEMENT =====
    readonly property int userProfile: plasmoidConfig.userProfile || 0
    readonly property var profileDefaults: ConfigManager.getProfileDefaults(userProfile)
    readonly property int maxHistoryItems: ConfigManager.getMaxHistoryItems(userProfile)
    
    // Feature flags based on profile
    readonly property bool debugEnabled: ConfigManager.isFeatureEnabled(userProfile, "debug")
    readonly property bool previewEnabled: ConfigManager.isFeatureEnabled(userProfile, "preview")
    readonly property bool advancedSearchEnabled: ConfigManager.isFeatureEnabled(userProfile, "advancedSearch")
    readonly property bool telemetryEnabled: ConfigManager.isFeatureEnabled(userProfile, "telemetry")
    readonly property bool categoryPriorityEnabled: ConfigManager.isFeatureEnabled(userProfile, "categoryPriority")
    readonly property bool activityPinningEnabled: ConfigManager.isFeatureEnabled(userProfile, "activityPinning")
    
    // Config validation
    function validateConfig() {
        return ConfigManager.sanitizeConfig({
            displayMode: plasmoidConfig.displayMode,
            viewMode: plasmoidConfig.viewMode,
            iconSize: plasmoidConfig.iconSize,
            listIconSize: plasmoidConfig.listIconSize,
            previewEnabled: plasmoidConfig.previewEnabled,
            debugOverlay: plasmoidConfig.debugOverlay,
            userProfile: plasmoidConfig.userProfile
        })
    }
    
    function getRecommendedIconSize() {
        return ConfigManager.getRecommendedIconSize(
            plasmoidConfig.displayMode,
            plasmoidConfig.viewMode
        )
    }
    
    // ===== HISTORY MANAGEMENT =====
    property var searchHistory: []
    
    // ===== PINNED ITEMS MANAGEMENT =====
    property var pinnedItems: []
    property string currentActivityId: "global"
    
    // ===== CATEGORY SETTINGS =====
    property var categorySettings: {}
    
    // ===== TELEMETRY =====
    property var telemetryStats: TelemetryManager.getStatsObject(plasmoidConfig.telemetryData || "{}")
    
    // ===== HISTORY FUNCTIONS =====
    function loadHistory() {
        // Debug: console.log("FileSearch [History]: Loading history...")
        searchHistory = HistoryManager.loadHistory(plasmoidConfig.searchHistory)
    }
    
    function saveHistory() {
        plasmoidConfig.searchHistory = JSON.stringify(searchHistory)
    }
    
    function addToHistory(display, decoration, category, matchId, filePath, sourceType, queryText) {
        searchHistory = HistoryManager.addToHistory(searchHistory, display, decoration, category, matchId, filePath, sourceType, queryText, plasmoidConfig.maxHistoryItems)
        saveHistory()
        
        // Schedule delayed icon check (1s)
        if (searchHistory.length > 0) {
            iconCheckTimer.uuid = searchHistory[0].uuid
            iconCheckTimer.filePath = filePath
            iconCheckTimer.decoration = decoration
            iconCheckTimer.category = category
            iconCheckTimer.restart()
        }
    }
    
    function formatHistoryTime(timestamp) {
        return Utils.formatHistoryTime(timestamp, i18n)
    }
    
    function clearHistory() {
        searchHistory = HistoryManager.clearHistory()
        saveHistory()
    }

    function removeFromHistory(uuid) {
        searchHistory = HistoryManager.removeFromHistory(searchHistory, uuid)
        saveHistory()
    }
    
    function executeCommand(command) {
        // Use the debug overlay's datasource pattern or similar mechanism if available
        // Since we don't have a global DataSource, we need to expose one here or usage site.
        // But for "Open With", "Trash", "Open Location", we need shell commands.
        // We will assume the view creates a DataSource for this purpose.
        // Or we can add one here.
    }
    
    // Global DataSource for shell commands
    Plasma5Support.DataSource {
        id: globalShellSource
        engine: "executable"
        connectedSources: []
        onNewData: (source, data) => {
            disconnectSource(source)
        }
    }
    
    function runShellCommand(cmd) {
        globalShellSource.connectedSources = [cmd]
    }
    
    // ===== FILE OPERATIONS =====
    function openFolder(url) {
        if (!url) return;
        var path = url.toString();
        // Use D-Bus to open file manager and select the item
        var cmd = "dbus-send --session --dest=org.freedesktop.FileManager1 /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:\"" + path + "\" string:\"\"";
        runShellCommand(cmd);
    }
    
    function copyToClipboard(text) {
        if (!text) return;
        // Using a reliable shell command for clipboard since QML clipboard is restricted in some environments
        var cmd = "echo -n '" + text.replace(/'/g, "'\\''") + "' | xclip -selection clipboard || echo -n '" + text.replace(/'/g, "'\\''") + "' | wl-copy";
        runShellCommand(cmd);
    }
    
    function moveToTrash(url) {
        if (!url) return;
        var path = url.toString();
        var cmd = "kioclient6 move \"" + path + "\" trash:/";
        runShellCommand(cmd);
    }
    
    function openTerminal(url) {
        if (!url) return;
        var path = url.toString().replace("file://", "");
        // If it's a file, get its directory
        if (path.indexOf(".") !== -1 && path.lastIndexOf("/") < path.lastIndexOf(".")) {
            path = path.substring(0, path.lastIndexOf("/"));
        }
        var cmd = "konsole --workdir \"" + path + "\"";
        runShellCommand(cmd);
    }
    
    // ===== ICON CHECK TIMER =====
    Timer {
        id: iconCheckTimer
        interval: 1000
        repeat: false
        property string uuid
        property string filePath
        property string decoration
        property string category
        
        onTriggered: {
            if (!uuid) return
            
            /// Only check if it has a file path
            if (filePath && filePath.toString().indexOf("file://") === 0) {
                // If decoration is broken (QIcon()) or missing
                if (decoration === "QIcon()" || decoration === "") {
                    // Set default folder icon temporarily if it's likely a folder
                    var isFolder = (category === "Yerler" || category === "Places" || category === "Klasörler");
                    
                    if (isFolder) {
                        HistoryManager.updateItemIcon(searchHistory, uuid, "folder");
                        saveHistory();
                        historyForceUpdate();
                    }
                    
                    // Try to fetch custom icon from .directory file
                    fetchDirectoryIcon(filePath, uuid);
                }
            }
        }
    }

    function fetchDirectoryIcon(folderPath, uuid) {
         if (!folderPath || folderPath.toString().indexOf("file://") !== 0) return;
         
         var request = new XMLHttpRequest();
         // Add .directory to path. Ensure no double slash if path ends with /
         var path = folderPath.toString();
         if (path.slice(-1) === "/") path = path.slice(0, -1);
         var url = path + "/.directory";
         
         request.open("GET", url);
         request.onreadystatechange = function() {
             if (request.readyState === XMLHttpRequest.DONE) {
                 if (request.status === 200 || request.status === 0) {
                     var content = request.responseText;
                     // Look for Icon=...
                     var lines = content.split('\n');
                     for (var i = 0; i < lines.length; i++) {
                         var line = lines[i].trim();
                         if (line.indexOf("Icon=") === 0) {
                             var iconName = line.substring(5).trim();
                             if (iconName.length > 0) {
                                 // Debug: console.log("FileSearch [Icon]: Found custom icon:", iconName);
                                 if (HistoryManager.updateItemIcon(logicRoot.searchHistory, uuid, iconName)) {
                                     logicRoot.saveHistory();
                                     logicRoot.historyForceUpdate();
                                 }
                                 return;
                             }
                         }
                     }
                 }
             }
         };
         request.send();
    }
    
    // ===== PINNED FUNCTIONS =====
    function loadPinned() {
        // Debug: console.log("FileSearch [Pinned]: Loading pinned items...")
        pinnedItems = PinnedManager.loadPinned(plasmoidConfig.pinnedItems)
    }
    
    function savePinned() {
        plasmoidConfig.pinnedItems = PinnedManager.savePinned(pinnedItems)
    }
    
    function pinItem(item) {
        pinnedItems = PinnedManager.pinItem(pinnedItems, item, currentActivityId)
        savePinned()
        pinnedItemsChanged()
    }
    
    function unpinItem(matchId) {
        pinnedItems = PinnedManager.unpinItem(pinnedItems, matchId, currentActivityId)
        savePinned()
        pinnedItemsChanged()
    }
    
    function isPinned(matchId) {
        return PinnedManager.isPinned(pinnedItems, matchId, currentActivityId)
    }
    
    function togglePin(item) {
        pinnedItems = PinnedManager.togglePin(pinnedItems, item, currentActivityId)
        savePinned()
        pinnedItemsChanged()
    }
    
    function getVisiblePinnedItems() {
        return visiblePinnedItems
    }
    
    // Reactive property for bindings
    readonly property var visiblePinnedItems: PinnedManager.getPinnedForActivity(pinnedItems, currentActivityId)
    
    function getPinInfo(matchId) {
        return PinnedManager.getPinInfo(pinnedItems, matchId, currentActivityId)
    }
    
    function reorderPinnedItems(fromIndex, toIndex) {
        pinnedItems = PinnedManager.reorderPinned(pinnedItems, fromIndex, toIndex)
        savePinned()
        pinnedItemsChanged()
    }
    
    // Activity management
    readonly property string currentActivityName: currentActivityId === "global" ? "Global" : currentActivityId
    
    function setActivity(activityId) {
        currentActivityId = activityId || "global"
    }
    
    function pinItemToActivity(item, activityId) {
        pinnedItems = PinnedManager.pinItem(pinnedItems, item, activityId || "global")
        savePinned()
        pinnedItemsChanged()
    }
    
    // ===== CATEGORY SETTINGS FUNCTIONS =====
    function loadCategorySettings() {
        // Debug: console.log("FileSearch [Category]: Loading category settings...")
        categorySettings = CategoryManager.loadCategorySettings(plasmoidConfig.categorySettings)
    }
    
    function processCategories(categories) {
        return CategoryManager.processCategories(categories, categorySettings)
    }
    
    function isCategoryVisible(categoryName) {
        return CategoryManager.isCategoryVisible(categorySettings, categoryName)
    }
    
    function getEffectiveIcon(categoryName, defaultIcon) {
        return CategoryManager.getEffectiveIcon(categorySettings, categoryName, defaultIcon)
    }
    
    function updateTelemetry(latency) {
        var newData = TelemetryManager.recordSearch(plasmoidConfig.telemetryData || "{}", latency)
        plasmoidConfig.telemetryData = newData
        telemetryStats = TelemetryManager.getStatsObject(newData)
    }

    // ===== DEPENDENCY CHECKS =====
    property bool manInstalled: true
    
    Plasma5Support.DataSource {
        id: manCheckSource
        engine: "executable"
        connectedSources: []
        onNewData: (source, data) => {
            if (data["exit code"] !== undefined) {
                logicRoot.manInstalled = (data["exit code"] === 0)
                disconnectSource(source)
            }
        }
    }

    function checkManAvailability() {
         manCheckSource.connectedSources = ["command -v man"]
    }

    // ===== RSS MANAGEMENT =====
    property var rssSources: []
    property var rssCache: []
    readonly property bool rssEnabled: plasmoidConfig.rssEnabled || false
    
    function loadRSS() {
        try {
            rssSources = JSON.parse(plasmoidConfig.rssSources || "[]")
            rssCache = JSON.parse(plasmoidConfig.rssCache || "[]")
        } catch (e) {
            rssSources = []
            rssCache = []
        }
    }
    
    Plasma5Support.DataSource {
        id: executable
        engine: "executable"
        connectedSources: []
    }

    function getSourceFilePath(url) {
        var base = StandardPaths.writableLocation(StandardPaths.CacheLocation) + "/plasma-file-search-rss"
        return RSSManager.getSourceFilePath(url, base)
    }

    function loadSourceEntries(url, callback) {
        if (!url) {
            callback([])
            return
        }
        var path = "file://" + getSourceFilePath(url)
        var xhr = new XMLHttpRequest()
        xhr.onreadystatechange = function() {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                if (xhr.status === 200 || xhr.status === 0) {
                    try {
                        var data = JSON.parse(xhr.responseText)
                        callback(data || [])
                    } catch(e) { callback([]) }
                } else {
                    callback([])
                }
            }
        }
        xhr.open("GET", path)
        xhr.send()
    }

    function checkAndSyncRSS() {
        if (!rssEnabled || rssSources.length === 0) return
        
        var now = new Date().getTime()
        for (var i = 0; i < rssSources.length; i++) {
            var source = rssSources[i]
            var interval = source.syncInterval || plasmoidConfig.rssSyncInterval || 60
            var intervalMs = interval * 60 * 1000
            var lastSync = source.lastSync || 0
            
            if (now - lastSync > intervalMs) {
                syncSource(i)
            }
        }
    }

    function syncSource(index) {
        var source = rssSources[index]
        if (!source.url) return
        
        fetchRSS(source, function(entries) {
            if (entries.length === 0) {
                // Keep old data if sync failed
                updateCombinedCache()
                return
            }
            
            rssSources[index].lastSync = new Date().getTime()
            plasmoidConfig.rssSources = JSON.stringify(rssSources)
            
            // Save to file
            var path = getSourceFilePath(source.url)
            var json = JSON.stringify(entries)
            var baseDir = StandardPaths.writableLocation(StandardPaths.CacheLocation) + "/plasma-file-search-rss"
            executable.exec("mkdir -p '" + baseDir + "' && cat << 'EOF' > '" + path + "'\n" + json + "\nEOF")
            
            updateCombinedCache()
        })
    }

    function syncAllRSS() {
        if (!rssEnabled || rssSources.length === 0) return
        for (var i = 0; i < rssSources.length; i++) {
            syncSource(i)
        }
    }

    function updateCombinedCache() {
        var combined = []
        var completedCount = 0
        
        if (rssSources.length === 0) {
            rssCache = []
            return
        }

        for (var i = 0; i < rssSources.length; i++) {
            loadSourceEntries(rssSources[i].url, function(entries) {
                combined = combined.concat(entries)
                completedCount++
                if (completedCount === rssSources.length) {
                    combined.sort(function(a, b) { return 0 })
                    rssCache = combined
                }
            })
        }
    }
    
    function hashStr(s) {
        var hash = 0
        for (var i = 0; i < s.length; i++) {
            hash = ((hash << 5) - hash) + s.charCodeAt(i)
            hash |= 0
        }
        return Math.abs(hash)
    }

    function fetchRSS(source, callback) {
        if (!source.url) {
            callback([])
            return
        }
        
        var xhr = new XMLHttpRequest()
        xhr.onreadystatechange = function() {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                if (xhr.status === 200) {
                    var entries = parseRSS(xhr.responseText, source.name)
                    var max = source.maxEntries || plasmoidConfig.rssMaxEntries || 10
                    callback(entries.slice(0, max))
                } else {
                    callback([])
                }
            }
        }
        xhr.open("GET", source.url)
        xhr.send()
    }

    function parseRSS(xml, sourceName) {
        return RSSManager.parseRSS(xml, sourceName)
    }

    Timer {
        id: rssSyncTimer
        interval: 60000 // Check every minute
        running: rssEnabled
        repeat: true
        onTriggered: checkAndSyncRSS()
    }
    
    // Watch for config changes (source addition/removal)
    Connections {
        target: plasmoidConfig
        function onRssSourcesChanged() {
            loadRSS()
            if (rssEnabled) syncAllRSS()
        }
        function onRssEnabledChanged() {
            if (rssEnabled) syncAllRSS()
        }
    }

    Component.onCompleted: {
        console.log("FileSearch: LogicController initialized")
        loadHistory()
        loadPinned()
        loadCategorySettings()
        loadRSS()
        updateCombinedCache()
        checkManAvailability()
        
        // Initial sync check
        Qt.callLater(() => {
            checkAndSyncRSS()
        })
    }
}
